set(SOURCES
	src/PCH.h
	src/Papyrus/Papyrus.cpp
	src/Papyrus/Papyrus.h
	src/Papyrus/PapyrusActor.h
	src/Papyrus/PapyrusCamera.h
	src/Papyrus/PapyrusDatabase.h
	src/Papyrus/PapyrusFace.h
	src/Papyrus/PapyrusObject.h
	src/Papyrus/PapyrusUtil.h
	src/Patch.h
	src/Util.cpp
	src/Util.h
	src/main.cpp
)
