set(SOURCES
	src/Game/LocaleManager.cpp
	src/Game/LocaleManager.h
	src/Game/Locker.h
	src/Game/Patch.h
	src/PCH.h
	src/Papyrus/Papyrus.cpp
	src/Papyrus/Papyrus.h
	src/Papyrus/PapyrusActor.h
	src/Papyrus/PapyrusCamera.h
	src/Papyrus/PapyrusDatabase.h
	src/Papyrus/PapyrusFace.h
	src/Papyrus/PapyrusObject.h
	src/Papyrus/PapyrusUtil.h
	src/Papyrus/Script.h
	src/Serial/Manager.cpp
	src/Serial/Manager.h
	src/Util.cpp
	src/Util.h
	src/main.cpp
)
